# Generated by Django 3.2 on 2022-03-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_atividade_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=2),
        ),
    ]
