# Generated by Django 2.2.12 on 2022-03-12 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_atividade_year_in_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('comentario', models.TextField(verbose_name='Comentário')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.CharField(max_length=100, verbose_name='Preço')),
                ('dias', models.IntegerField(verbose_name='Quantidade de dias na semana')),
                ('horario', models.CharField(choices=[('MANHÃ', 'MANHÃ'), ('TARDE', 'TARDE'), ('NOITE', 'NOITE'), ('FLEXÍVEL', 'FLEXÍVEL')], max_length=10, verbose_name='Horário')),
                ('detalhes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('metodologia', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('aula', models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3, verbose_name='Aulas particulares?')),
            ],
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Campo',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Plano'),
        ),
    ]
