# Generated by Django 2.2.12 on 2022-04-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20220320_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='foto',
            field=models.FileField(blank=True, upload_to='imgs/'),
        ),
    ]
